@host =http://localhost:5153

post {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"omar",
    "lastName":"betar",
    "email":"omar@betar.com",
    "password":"1234"
}


####